### ISSUE TITLE
Change default time span thats loaded

### ISSUE THREAD

**Issue by AlertSubject** [owntracks/frontend#53]
Another nice change would be changing the default time span that's loaded when opening the web interface.
The current default is one month. I'd much rather set it to a week or something like this because it would speed up loading times a lot, especially if I'm just checking something that has happened a few days ago.

IMO the best option would be an option in the GUI to let the user select between, lets say, today, a week and a month.
And whatever the user chooses would be the new default for when the frontend is being loaded

**Comment by linusg** [comment]
> Another nice change would be changing the default time span that's loaded when opening the web interface.
The current default is one month. I'd much rather set it to a week or something like this because it would speed up loading times a lot, especially if I'm just checking something that has happened a few days ago.

You can change already this, see [`startDateTime` in the config docs](https://github.com/owntracks/frontend/blob/master/docs/config.md#startdatetime).

**Comment by AlertSubject** [comment]
Would a GUI option in the frontend be an option?

**Comment by linusg** [comment]
No, I'm not going to implement any per-browser settings, and this would require that since there's no API to save such an option change serverside.

**Comment by michaelvandorpe** [comment]
How would I configure startDateTime to load “Today” by default?
Thanks!

**Comment by linusg** [comment]
Like in the example linked above, but omitting setDate.
