### ISSUE TITLE
Include precompiled dist/ in releases

### ISSUE THREAD

**Issue by atlib77** [owntracks/frontend#90]
Any reason not to? Would make it a lot simpler for most to install the Frontend on web server

**Comment by linusg** [comment]
If you make a PR to automate this, sure :)

**Comment by atlib77** [comment]
:)  how are you currently deploying the releases? Fully manually?
I guess enhancing the build github action to include a deployment shouldn't be more then a few lines. Wouldn't you do it like that?

**Comment by paclg** [comment]
Hello, I think it would be a nice idea. I had to struggle with dependencies for compile it.
And, at the moment, it works but I can't figure why I have a big blank window instead of the leaflet map... and no error messages in the console.
I receive the data from recorder, it's ok and the basic web frontend of recorder works... but no map here :-(

**Comment by linusg** [comment]
Via the GitHub UI, which in turn creates a git tag (considered a "release"), which in turn triggers this GitHub action for the Docker image build:

https://github.com/owntracks/frontend/blob/9bb2edb78d5ea23a19a9e528b263a1555c0301eb/.github/workflows/docker.yml#L12-L16

**Comment by jpmens** [comment]
We'd be interested in `dist/` releases as well for [Frontend installation in quicksetup](https://github.com/owntracks/quicksetup/blob/af39f723b8d4d80f8bd633b7df12695625d5bdfa/owntracks-setup.yml#L346).
